[package]
name = "mcp_test_support"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"
test = false
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
codex-login = { workspace = true }
codex-mcp-server = { workspace = true }
codex-terminal-detection = { workspace = true }
codex-utils-cargo-bin = { workspace = true }
rmcp = { workspace = true }
os_info = { workspace = true }
pretty_assertions = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["alloc"] }
tokio = { workspace = true, features = [
    "io-std",
    "io-util",
    "macros",
    "process",
    "rt-multi-thread",
] }
wiremock = { workspace = true }
core_test_support = { path = "../../../core/tests/common", default-features = false }
shlex = { workspace = true, features = ["std"] }
