[package]
edition.workspace = true
license.workspace = true
name = "codex-utils-pty"
version.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
portable-pty = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "process", "rt-multi-thread", "sync", "time"] }

[dev-dependencies]
pretty_assertions = { workspace = true, features = ["std"] }

[target.'cfg(windows)'.dependencies]
filedescriptor = { version = "0.8.3", default-features = false }
lazy_static = { workspace = true }
log = { workspace = true }
shared_library = { version = "0.1.9", default-features = false }
winapi = { default-features = false, version = "0.3.9", features = [
    "handleapi",
    "jobapi",
    "jobapi2",
    "libloaderapi",
    "minwinbase",
    "processthreadsapi",
    "synchapi",
    "winbase",
    "wincon",
    "winerror",
    "winnt",
] }
[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[lib]
doctest = false
