[package]
edition.workspace = true
license.workspace = true
name = "codex-utils-audio"
version.workspace = true

[lints]
workspace = true

[dependencies]
base64 = { workspace = true, features = ["std"] }
codex-protocol = { workspace = true }
codex-utils-cache = { workspace = true }
codex-utils-string = { workspace = true }
symphonia = { workspace = true, features = ["isomp4", "mkv", "mp3", "ogg", "wav"] }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true, features = ["std"] }

[lib]
doctest = false
