// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionText } from "./ConnectionText";

export type ConnectionLoginChallenge = { "type": "browser", url: ConnectionText, } | { "type": "deviceCode", url: ConnectionText, code: ConnectionText, };
