// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionText } from "./ConnectionText";
import type { SavedConnectionProvider } from "./SavedConnectionProvider";

export type SavedConnectionParams = { "action": "list", activeProvider: ConnectionText, } | { "action": "add", provider: SavedConnectionProvider, name: ConnectionText, } | { "action": "prepare", id: ConnectionText, } | { "action": "select", id: ConnectionText, switchId: ConnectionText, } | { "action": "commit", switchId: ConnectionText, } | { "action": "restore", switchId: ConnectionText, };
