// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionLoginChallenge } from "./ConnectionLoginChallenge";
import type { ConnectionText } from "./ConnectionText";
import type { Model } from "./Model";
import type { SavedConnectionInfo } from "./SavedConnectionInfo";

export type SavedConnectionResponse = { "type": "connections", data: Array<SavedConnectionInfo>, } | { "type": "prepared", data: Array<Model>, } | { "type": "selected", switchId: ConnectionText, } | { "type": "loginStarted", loginId: ConnectionText, challenge: ConnectionLoginChallenge, } | { "type": "settled" };
