// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionSelection } from "./ConnectionSelection";
import type { ConnectionText } from "./ConnectionText";
import type { SavedConnectionProvider } from "./SavedConnectionProvider";

export type SavedConnectionInfo = { id: ConnectionText, name: ConnectionText, provider: SavedConnectionProvider, selection: ConnectionSelection, };
