[package]
name = "app_test_support"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
base64 = { workspace = true, features = ["alloc"] }
chrono = { workspace = true, features = ["clock"] }
codex-app-server-protocol = { workspace = true }
codex-config = { workspace = true }
codex-core = { workspace = true }
codex-exec-server = { workspace = true }
codex-features = { workspace = true }
codex-login = { workspace = true }
codex-models-manager = { workspace = true }
codex-protocol = { workspace = true }
codex-utils-cargo-bin = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["alloc"] }
tempfile = { workspace = true, features = ["getrandom"] }
tokio = { workspace = true, features = [
    "io-util",
    "io-std",
    "macros",
    "net",
    "process",
    "rt-multi-thread",
    "test-util",
] }
tokio-util = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
wiremock = { workspace = true }
core_test_support = { path = "../../../core/tests/common", default-features = false }
shlex = { workspace = true, features = ["std"] }

[dev-dependencies]
pretty_assertions = { workspace = true, features = ["std"] }
