[package]
name = "codex-file-search"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "codex-file-search"
path = "src/main.rs"

[lib]
name = "codex_file_search"
path = "src/lib.rs"
doctest = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
clap = { workspace = true, features = ["derive", "std"] }
crossbeam-channel = { workspace = true, features = ["std"] }
ignore = { workspace = true }
nucleo = { workspace = true }
serde = { workspace = true, features = ["derive", "std"] }
serde_json = { workspace = true, features = ["alloc"] }
tokio = { workspace = true, features = ["macros", "process", "rt-multi-thread"] }

[dev-dependencies]
pretty_assertions = { workspace = true, features = ["std"] }
tempfile = { workspace = true, features = ["getrandom"] }
