exports_files([
    "clippy.toml",
])

filegroup(
    name = "workspace-files",
    srcs = glob(
        [
            "*",
            ".cargo/**",
        ],
        exclude = [
            "BUILD.bazel",
        ],
    ),
    visibility = ["//visibility:public"],
)

test_suite(
    name = "e2e-benchmarks",
    tags = ["manual"],
    tests = [
        "//codex-rs/cli:codex-help-bench",
        "//codex-rs/code-mode-host:stdio-throughput-bench",
        "//codex-rs/code-mode-host:websocket-throughput-bench",
        "//codex-rs/exec:codex-exec-bench",
    ],
    visibility = ["//visibility:public"],
)
