[package]
name = "argument_comment_lint"
version = "0.1.0"
description = "Dylint lints for Rust /*param*/ argument comments"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
bazel_native = []

[dependencies]
clippy_utils = { git = "https://github.com/rust-lang/rust-clippy", rev = "20ce69b9a63bcd2756cd906fe0964d1e901e042a", default-features = false }
dylint_linting = { version = "5.0.0", default-features = false }

[dev-dependencies]
dylint_testing = { version = "5.0.0", default-features = false }

[workspace]

[package.metadata.rust-analyzer]
rustc_private = true
