[package]
name = "codex-responses-api-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "codex_responses_api_proxy"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "codex-responses-api-proxy"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
clap = { workspace = true, features = ["derive", "std"] }
codex-process-hardening = { workspace = true }
ctor = { workspace = true, features = ["proc_macro"] }
libc = { workspace = true }
reqwest = { workspace = true, features = [
    "blocking",
    "http2",
    "json",
    "rustls-tls",
    "system-proxy",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["alloc"] }
tiny_http = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true, features = ["std"] }
