// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Selects the OpenAI Responses API reasoning execution mode.
 */
export type ReasoningMode = "standard" | "pro";
