[package]
name = "codex-otel"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
doctest = false
name = "codex_otel"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
chrono = { workspace = true, features = ["clock"] }
codex-utils-absolute-path = { workspace = true }
codex-utils-string = { workspace = true }
codex-api = { workspace = true }
codex-protocol = { workspace = true }
eventsource-stream = { workspace = true }
gethostname = { workspace = true }
opentelemetry = { workspace = true, features = ["logs", "metrics", "trace"] }
opentelemetry-appender-tracing = { workspace = true }
opentelemetry-otlp = { workspace = true, features = [
    "grpc-tonic",
    "http-proto",
    "http-json",
    "logs",
    "metrics",
    "trace",
    "reqwest-blocking-client",
    "reqwest-rustls",
    "tls",
    "tls-roots",
] }
opentelemetry-semantic-conventions = { workspace = true }
opentelemetry_sdk = { workspace = true, features = [
    "experimental_trace_batch_span_processor_with_async_runtime",
    "experimental_metrics_custom_reader",
    "testing",
] }
http = { workspace = true }
os_info = { workspace = true }
reqwest = { workspace = true, features = [
    "blocking",
    "http2",
    "rustls-tls",
    "system-proxy",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["alloc"] }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time"] }
tokio-tungstenite = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["registry"] }

[dev-dependencies]
opentelemetry_sdk = { workspace = true, features = [
    "experimental_metrics_custom_reader",
    "testing",
] }
pretty_assertions = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[target.'cfg(unix)'.dev-dependencies]
libc = { workspace = true }

[target.'cfg(target_os = "linux")'.dev-dependencies]
seccompiler = { workspace = true }
