[package]
name = "codex-feedback"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
codex-http-client = { workspace = true }
codex-login = { workspace = true }
codex-protocol = { workspace = true }
mime_guess = { workspace = true }
sentry = { version = "0.46", default-features = false }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt"] }

[dev-dependencies]
log = { workspace = true }
pretty_assertions = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["macros", "rt"] }
wiremock = { workspace = true }

[lib]
doctest = false
