[package]
edition.workspace = true
license.workspace = true
name = "codex-model-provider-info"
version.workspace = true

[lib]
doctest = false
name = "codex_model_provider_info"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
codex-api = { workspace = true }
codex-protocol = { workspace = true }
codex-utils-redacted-string = { workspace = true }
http = { workspace = true }
schemars = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
codex-utils-absolute-path = { workspace = true }
maplit = { workspace = true }
pretty_assertions = { workspace = true, features = ["std"] }
tempfile = { workspace = true, features = ["getrandom"] }
toml = { workspace = true, features = ["parse", "serde", "std"] }
