[package]
name = "codex-git-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
chrono = { workspace = true, features = ["clock"] }
codex-file-system = { workspace = true }
codex-protocol = { workspace = true }
codex-utils-absolute-path = { workspace = true }
codex-utils-path-uri = { workspace = true }
codex-utils-pty = { workspace = true }
futures = { workspace = true, features = ["alloc"] }
gix = { workspace = true, features = ["sha1"] }
once_cell = { workspace = true, features = ["std"] }
regex = { workspace = true, features = ["perf", "std", "unicode"] }
schemars = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
similar = { workspace = true, features = ["text"] }
tempfile = { workspace = true, features = ["getrandom"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "macros", "process", "rt", "time"] }
ts-rs = { workspace = true, features = [
    "serde-compat",
    "uuid-impl",
    "serde-json-impl",
    "no-serde-warnings",
] }
walkdir = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = ["sync"] }

[lib]
doctest = false
